### ISSUE TITLE
Error IllegalArgumentException: location after #98

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/TitansBattle#101]
```
[18:36:28] [Server thread/WARN]: [TitansBattle] Task #85618 for TitansBattle v6.2.1-SNAPSHOT-bbe0331 generated an exception
java.lang.IllegalArgumentException: location
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:145) ~[guava-31.1-jre.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.entity.CraftPlayer.teleport(CraftPlayer.java:1341) ~[purpur-1.19.4.jar:git-Purpur-1968]
	at org.bukkit.craftbukkit.v1_19_R3.entity.CraftPlayer.teleport(CraftPlayer.java:1274) ~[purpur-1.19.4.jar:git-Purpur-1968]
	at org.bukkit.craftbukkit.v1_19_R3.entity.CraftEntity.teleport(CraftEntity.java:564) ~[purpur-1.19.4.jar:git-Purpur-1968]
	at me.roinujnosde.titansbattle.BaseGame.teleport(BaseGame.java:336) ~[TitansBattle-6.2.1-SNAPSHOT.jar:?]
	at me.roinujnosde.titansbattle.BaseGame.lambda$teleport$6(BaseGame.java:532) ~[TitansBattle-6.2.1-SNAPSHOT.jar:?]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at me.roinujnosde.titansbattle.BaseGame.teleport(BaseGame.java:532) ~[TitansBattle-6.2.1-SNAPSHOT.jar:?]
	at me.roinujnosde.titansbattle.BaseGame.teleportToArena(BaseGame.java:551) ~[TitansBattle-6.2.1-SNAPSHOT.jar:?]
	at me.roinujnosde.titansbattle.games.FreeForAllGame.onLobbyEnd(FreeForAllGame.java:67) ~[TitansBattle-6.2.1-SNAPSHOT.jar:?]
	at me.roinujnosde.titansbattle.BaseGame$LobbyAnnouncementTask.processEnd(BaseGame.java:610) ~[TitansBattle-6.2.1-SNAPSHOT.jar:?]
	at me.roinujnosde.titansbattle.BaseGame$LobbyAnnouncementTask.run(BaseGame.java:603) ~[TitansBattle-6.2.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftTask.run(CraftTask.java:101) ~[purpur-1.19.4.jar:git-Purpur-1968]
	at org.bukkit.craftbukkit.v1_19_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483) ~[purpur-1.19.4.jar:git-Purpur-1968]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1510) ~[purpur-1.19.4.jar:git-Purpur-1968]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.19.4.jar:git-Purpur-1968]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1424) ~[purpur-1.19.4.jar:git-Purpur-1968]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1195) ~[purpur-1.19.4.jar:git-Purpur-1968]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:325) ~[purpur-1.19.4.jar:git-Purpur-1968]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by RoinujNosde** [comment]
Are the arena entrances set?

**Comment by Tomut0** [comment]
Can you try the latest build? 
https://ci.roinujnosde.me/job/TitansBattle/168/artifact/target/TitansBattle-6.2.1-SNAPSHOT.jar
