### ISSUE TITLE
1.20.1

### ISSUE THREAD

**Issue by LucasHenriqueDG** [RoinujNosde/TitansBattle#109]
[12:59:12] [Server thread/ERROR]: Could not pass event PlayerJoinEvent to TitansBattle v6.2.1-SNAPSHOT-473e06c
me.roinujnosde.titansbattle.shaded.nbtapi.NbtApiException: [?]Error while calling the method 'getBoolean(java.lang.String)', loaded: true, Enum: COMPOUND_GET_BOOLEAN, Passed Class: class java.lang.Boolean
	at me.roinujnosde.titansbattle.shaded.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:358) ~[TitansBattle-6.2.1-SNAPSHOT(1).jar:?]
	at me.roinujnosde.titansbattle.shaded.nbtapi.NBTReflectionUtil.getData(NBTReflectionUtil.java:635) ~[TitansBattle-6.2.1-SNAPSHOT(1).jar:?]
	at me.roinujnosde.titansbattle.shaded.nbtapi.NBTCompound.getBoolean(NBTCompound.java:438) ~[TitansBattle-6.2.1-SNAPSHOT(1).jar:?]
	at me.roinujnosde.titansbattle.listeners.ItemsProtectionListener.process(ItemsProtectionListener.java:53) ~[TitansBattle-6.2.1-SNAPSHOT(1).jar:?]
	at me.roinujnosde.titansbattle.listeners.ItemsProtectionListener.on(ItemsProtectionListener.java:39) ~[TitansBattle-6.2.1-SNAPSHOT(1).jar:?]
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor534.execute(Unknown Source) ~[?:?]
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:git-Purpur-1996]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
	at net.minecraft.server.players.PlayerList.placeNewPlayer(PlayerList.java:339) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.placeNewPlayer(ServerLoginPacketListenerImpl.java:202) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.handleAcceptedLogin(ServerLoginPacketListenerImpl.java:183) ~[?:?]
	at net.minecraft.server.network.ServerLoginPacketListenerImpl.tick(ServerLoginPacketListenerImpl.java:85) ~[?:?]
	at net.minecraft.network.Connection.tick(Connection.java:608) ~[?:?]
	at net.minecraft.server.network.ServerConnectionListener.tick(ServerConnectionListener.java:234) ~[?:?]
	at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1602) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:487) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1421) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1192) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:323) ~[purpur-1.20.1.jar:git-Purpur-1996]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at me.roinujnosde.titansbattle.shaded.nbtapi.utils.nmsmappings.ReflectionMethod.run(ReflectionMethod.java:355) ~[TitansBattle-6.2.1-SNAPSHOT(1).jar:?]
	... 23 more

**Comment by Tomut0** [comment]
I think @thiagogebrimm was fixed it in the latest development build.
You can download it here: https://ci.roinujnosde.me/job/TitansBattle/173/
