### ISSUE TITLE
Problemas com o modo GROUPS_REAL

### ISSUE THREAD

**Issue by SrBedrock** [RoinujNosde/TitansBattle#6]
Acredito que seja devido ao game info.

Erro:

```
[19:21:49 WARN]: [TitansBattle] Task #3135814 for TitansBattle v3.0.2 generated an exception
java.lang.NullPointerException: null
at me.roinujnosde.titansbattle.Helper.lambda$getStringFromGroupSet$3(Helper.java:860) ~[?:?]
at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195) ~[?:?]
at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1694) ~[?:?]
at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484) ~[?:?]
at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474) ~[?:?]
at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913) ~[?:?]
at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:?]
at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578) ~[?:?]
at me.roinujnosde.titansbattle.Helper.getStringFromGroupSet(Helper.java:860) ~[?:?]
at me.roinujnosde.titansbattle.managers.TaskManager$ArenaAnnouncementTask$1.run(TaskManager.java:198) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.15.2.jar:git-Tuinity-"eedc3fc"]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.15.2.jar:git-Tuinity-"eedc3fc"]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1324) ~[patched_1.15.2.jar:git-Tuinity-"eedc3fc"]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:432) ~[patched_1.15.2.jar:git-Tuinity-"eedc3fc"]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1239) ~[patched_1.15.2.jar:git-Tuinity-"eedc3fc"]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:970) ~[patched_1.15.2.jar:git-Tuinity-"eedc3fc"]
at java.lang.Thread.run(Thread.java:832) [?:?]
```

Config: https://hasteb.in/axayadib.yaml

**Comment by RoinujNosde** [comment]
@SrBedrock poderia reenviar a config?
